title: "Red Team Research Blog"
description: "Defensive and offensive cybersecurity research, red teaming insights, and lab-based demonstrations."
baseurl: ""
url: "https://tanc7.github.io/crackamphetamine.github.io/"
theme: minima
markdown: kramdown
