title: "Red Team Research Blog"
description: "Lab-based red teaming and cybersecurity research"
baseurl: "/crackamphetamine.github.io"  # important for project sites
url: "https://tanc7.github.io"
theme: minima
markdown: kramdown
